#!/bin/bash
cd lib
make libs
cd ..
cd Merger2to1
make
cd ..
cd Merger2to1A
make
cd ..
cd Merger2to1B
make
cd ..
cd Merger2to1Z
make
cd ..
cd Merger4to1
make
cd ..
cd Merger4to1A
make
cd ..
cd Merger4to1B
make
cd ..
cd TPClogger
make
cd ..
cd DumGenA
make
cd ..
cd DumGenB
make
cd ..
if [ -e /usr/share/swsoc8 -o -e /usr/share/swpci ]; then
    cd TPCreader
    make
    cd ..
    cd TPCreaderA
    make
    cd ..
    cd TPCreaderB
    make
    cd ..
    cd TPCreaderC
    make
    cd ..
    cd TPCreaderD
    make
    cd ..
    cd TPCreaderZ
    make
    cd ..
fi
cd utils
make aps
cd ..
