#!/bin/bash
MACHINE=$(uname -m)
HARDWARE=$(uname -i)
if [ "$MACHINE" = armv7l ]; then
    if [ "$HARDWARE" = armv7l ]; then
        only_daqmw=no
    fi
fi
if [ "$MACHINE" = armv7l ]; then
    if [ "$HARDWARE" = unknown ]; then
        only_daqmw=yes
    fi
fi
if [ "$MACHINE" = x86_64 ]; then
    only_daqmw=no
fi

cd lib
make
cd ..
cd Merger2to1
make
cd ..
cd Merger2to1A
make
cd ..
cd Merger2to1B
make
cd ..
cd Merger4to1
make
cd ..
cd TPClogger
make
cd ..
if [ "$only_daqmw" = no ]; then
    cd TPCreader
    make
    cd ..
    cd TPCreaderA
    make
    cd ..
    cd TPCreaderB
    make
    cd ..
    cd TPCreaderC
    make
    cd ..
    cd TPCreaderD
    make
    cd ..
    cd utils
    make
    cd ..
fi

