# Makefile for sw

LDFLAGS = -I../lib/
LOADLIBS =
LDLIBS = ../lib/tpcmath.o ../lib/trigio_lib.o -lm -lrt
APS = analped analdata analpeak analmwbuf
APS += trigio_read trigio_rdone trigio_cntrst

.c.o:
	$(CC) -Wall -c $*.c -o $@

## Aps

aps : $(APS)

##analmwbuf: analmwbuf.c
##	$(CC) -Wall -o analmwbuf analmwbuf.c

#
clean:
	rm -f *.o *~ $(APS)

